In [1]:
import  pandas as pd , numpy as np , matplotlib.pyplot as plt , seaborn as sns

In [2]:
ds = pd.read_csv("employee.csv")

In [3]:
ds.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [4]:
ds.shape

(1470, 35)

In [6]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [7]:
ds.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [8]:
ds.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

TASK

1. Analyze employee attrition patterns.

In [11]:
ds['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [12]:
ds.groupby('Gender')['Attrition'].value_counts()

Gender  Attrition
Female  No           501
        Yes           87
Male    No           732
        Yes          150
Name: count, dtype: int64

2. Study salary impact on attrition

In [13]:
ds.groupby('PercentSalaryHike')['Attrition'].value_counts()

PercentSalaryHike  Attrition
11                 No           169
                   Yes           41
12                 No           165
                   Yes           33
13                 No           175
                   Yes           34
14                 No           177
                   Yes           24
15                 No            83
                   Yes           18
16                 No            64
                   Yes           14
17                 No            68
                   Yes           14
18                 No            76
                   Yes           13
19                 No            67
                   Yes            9
20                 No            48
                   Yes            7
21                 No            43
                   Yes            5
22                 No            44
                   Yes           12
23                 No            22
                   Yes            6
24                 No            15
                   Yes            6
25                 No            17
                   Yes            1
Name: count, dtype: int64

3. Analyse department wise turnover

In [16]:
emp_in_dept = ds['Department'].value_counts()
emp_in_dept

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [39]:
emp_attrition_dept= ds.groupby('Department')['Attrition'].value_counts()
emp_left_dept=emp_attrition_dept.xs("No",level="Attrition")
emp_left_dept

Department
Human Resources            51
Research & Development    828
Sales                     354
Name: count, dtype: int64

In [40]:
total_emp_deptwise = ds.groupby('Department')['EmployeeCount'].sum()
total_emp_deptwise

Department
Human Resources            63
Research & Development    961
Sales                     446
Name: EmployeeCount, dtype: int64

In [41]:
turnover = (emp_left_dept*100)/total_emp_deptwise

In [42]:
turnover

Department
Human Resources           80.952381
Research & Development    86.160250
Sales                     79.372197
dtype: float64

4 . Investigate overtimr effects

In [43]:
ds.groupby('OverTime')['PercentSalaryHike'].value_counts()

OverTime  PercentSalaryHike
No        11                   149
          14                   145
          13                   144
          12                   139
          15                    80
          17                    66
          18                    60
          16                    55
          19                    55
          22                    41
          20                    40
          21                    36
          23                    19
          25                    13
          24                    12
Yes       13                    65
          11                    61
          12                    59
          14                    56
          18                    29
          16                    23
          15                    21
          19                    21
          17                    16
          20                    15
          22                    15
          21                    12
          23                     9
          24                     9
          25                     5
Name: count, dtype: int64

5. Recommend retention strategies

In [47]:
emp_remaining_dept = emp_attrition_dept.xs("Yes",level ="Attrition")
emp_remaining_dept

Department
Human Resources            12
Research & Development    133
Sales                      92
Name: count, dtype: int64

In [48]:
retention_rate = emp_remaining_dept*100 / total_emp_deptwise
retention_rate

Department
Human Resources           19.047619
Research & Development    13.839750
Sales                     20.627803
dtype: float64